name: 'Conventional Commits PR'
description: 'Validate a pull request title against a Conventional Commits preset.'
inputs:
  auto-install:
    description: 'Auto-install dependencies and the conventional changelog config package.'
    required: false
    default: true
  config-preset:
    description: 'Name of conventional changelog config preset.'
    required: false
    default: 'beemo'
  config-version:
    description: 'Version of conventional changelog config package to install.'
    required: false
    default: 'latest'
  require-multiple-commits:
    description: 'Squash merges require multiple commits for the PR title to be preserved.'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'git-pull-request'
  color: 'red'
